CREATE DATABASE DB_PIZZARIA_LEGAL;

USE DB_PIZZARIA_LEGAL;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255),
BORDA VARCHAR(255),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PIZZAS(
ID BIGINT AUTO_INCREMENT,
SABOR VARCHAR(255),
DESCRICAO VARCHAR(1000),
TAMANHO CHAR(255),
PRECO DOUBLE,
PRIMARY KEY (ID),
CATEGORIAS_ID BIGINT,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (TIPO,BORDA) VALUES ("DOCE","NORMAL");
INSERT INTO TB_CATEGORIAS (TIPO,BORDA) VALUES ("SALGADA","RECHEADA");
INSERT INTO TB_CATEGORIAS (TIPO,BORDA) VALUES ("DOCE","RECHEADA");
INSERT INTO TB_CATEGORIAS (TIPO,BORDA) VALUES ("SALGADA","NORMAL");
INSERT INTO TB_CATEGORIAS (TIPO,BORDA) VALUES ("MEIO A MEIO","NORMAL");

INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("CHOCOLATE","CHOCOLATE AO LEITE E GRANULADO","GRANDE",46.00,3);
INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("PRESTIGIO","CHOCOLATE E COCO RALADO","PEQUENA",28.00,1);
INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("MUSSARELA/CALABRESA","MUSSARELA FATIADA/CALABRESA COM CEBOLA","GRANDE",35.00,5);
INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("FRANGO COM CATUPIRY","FRANGO DESFIADO COM CATUPIRY","PEQUENA",25.00,4);
INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("ATUM","ATUM E CEBOLA","PEQUENA",28.00,4);
INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("DOIS QUEIJOS","MUSSARELA FATIADA E CATUPIRY","GRANDE",40.00,2);
INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("M&M's","CHOCOLATE E M&M'S","PEQUENA",26.00,1);
INSERT INTO TB_PIZZAS (SABOR,DESCRICAO,TAMANHO,PRECO,CATEGORIAS_ID) VALUES ("CAIPIRA","FRANGO DESFIADO,MILHO E CATUPIRY","GRANDE",40.00,2);

SELECT * FROM TB_PIZZAS WHERE PRECO > 45.00;
SELECT * FROM TB_PIZZAS WHERE PRECO BETWEEN 50.00 AND 100.00;
SELECT * FROM TB_PIZZAS WHERE SABOR LIKE "%M%";

SELECT * FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID;

SELECT TB_PIZZAS.SABOR, TB_PIZZAS.DESCRICAO, TB_PIZZAS.TAMANHO, TB_PIZZAS.PRECO FROM TB_PIZZAS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PIZZAS.CATEGORIAS_ID WHERE TIPO = "DOCE";
