CREATE DATABASE DB_FARMACIA_BEM_ESTAR;

USE DB_FARMACIA_BEM_ESTAR;

CREATE TABLE TB_CATEGORIAS(
ID BIGINT AUTO_INCREMENT,
TIPO VARCHAR(255),
FUNCAO VARCHAR(255),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
MG VARCHAR(1000),
QTD VARCHAR(255),
PRECO DOUBLE,
PRIMARY KEY (ID),
CATEGORIAS_ID BIGINT,
FOREIGN KEY (CATEGORIAS_ID) REFERENCES TB_CATEGORIAS(ID)
);

INSERT INTO TB_CATEGORIAS (TIPO,FUNCAO) VALUES ("ANALGESICO","PARA ACABAR COM A DOR");
INSERT INTO TB_CATEGORIAS (TIPO,FUNCAO) VALUES ("ANTI-INFLAMATORIO","AMENIZAR SINTOMAS COMUNS DA INFLAMAÇÃO");
INSERT INTO TB_CATEGORIAS (TIPO,FUNCAO) VALUES ("ANTIBIOTICO","TRATAR INFECÇÕES BACTERIANAS");
INSERT INTO TB_CATEGORIAS (TIPO,FUNCAO) VALUES ("ANTIALERGICO","TRATAR ALERGIAS");
INSERT INTO TB_CATEGORIAS (TIPO,FUNCAO) VALUES ("ANTIACIDO","ALIVIAR AZIA E DORES NO ESTÔMAGO");

SELECT * FROM TB_CATEGORIAS;

INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("DIPIRONA","500mg","10cp",2.00,1);
INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("TYLENOL","750mg","30cp",45.90,1);
INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("OMEPRAZOL","20mg","56capsulas",8.99,5);
INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("CEFALEXINA","500mg","40cp",66.00,3);
INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("IBUPROFENO","600mg","20cp",15.00,2);
INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("DICLOFENACO","50mg","20cp",7.00,2);
INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("LORATADINA","10mg","12cp",6.00,4);
INSERT INTO TB_PRODUTOS (NOME,MG,QTD,PRECO,CATEGORIAS_ID) VALUES ("DORFLEX","300mg","10cp",5.50,1);

SELECT * FROM TB_PRODUTOS WHERE PRECO > 50.00;
SELECT * FROM TB_PRODUTOS WHERE PRECO BETWEEN 5.00 AND 60.00;
SELECT * FROM TB_PRODUTOS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID;

SELECT TB_PRODUTOS.NOME, TB_PRODUTOS.MG, TB_PRODUTOS.QTD, TB_PRODUTOS.PRECO FROM TB_PRODUTOS INNER JOIN TB_CATEGORIAS ON TB_CATEGORIAS.ID = TB_PRODUTOS.CATEGORIAS_ID WHERE TIPO = "ANALGESICO";
