CREATE DATABASE DB_GENERATION_GAME_ONLINE;

USE DB_GENERATION_GAME_ONLINE;

CREATE TABLE TB_CLASSES(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
ARMA VARCHAR(255),
DESCRICAO VARCHAR(1000),
PRIMARY KEY (ID)
);

CREATE TABLE TB_PERSONAGENS(
ID BIGINT AUTO_INCREMENT,
NOME VARCHAR(255),
RACA VARCHAR(255),
ATAQUE DOUBLE,
DEFESA DOUBLE,
PRIMARY KEY (ID),
CLASSE_ID BIGINT,
FOREIGN KEY (CLASSE_ID) REFERENCES TB_CLASSES(ID)
);

INSERT INTO TB_CLASSES (NOME,ARMA,DESCRICAO) VALUES ("Dark Knight","Espadas","Combate corpo a corpo");
INSERT INTO TB_CLASSES (NOME,ARMA,DESCRICAO) VALUES ("Dark Wizard","Cajados","Especialista em magias");
INSERT INTO TB_CLASSES (NOME,ARMA,DESCRICAO) VALUES ("Fairy Elf","Arcos","Suporte em guerras");
INSERT INTO TB_CLASSES (NOME,ARMA,DESCRICAO) VALUES ("Magic Gladiator","Espadas Magicas","guerreiro versatil");
INSERT INTO TB_CLASSES (NOME,ARMA,DESCRICAO) VALUES ("Dark Lord","Cetro","Especialista em magia negra");

INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("Thor","Guerreiro",3800,2555,1);
INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("Robin Hood","Guerreiro",2800,2300,1);
INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("Dr Estranho","Mago",1800,1830,2);
INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("Loki","Mago",3600,3023,5);
INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("Deedlit","Fada Duende",1200,1500,3);
INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("Kallark","Gladiador Magico",2100,2100,4);
INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("General", "Gladiador Magico",3000,2800,4);
INSERT INTO TB_PERSONAGENS (NOME,RACA,ATAQUE,DEFESA,CLASSE_ID) VALUES ("Punisher","Guerreiro",5000,3855,1);

SELECT * FROM TB_PERSONAGENS WHERE ATAQUE > 2000;
SELECT * FROM TB_PERSONAGENS WHERE DEFESA BETWEEN 1000 AND 2000;
SELECT * FROM TB_PERSONAGENS WHERE NOME LIKE "%C%";

SELECT * FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGENS.CLASSE_ID;

SELECT TB_PERSONAGENS.NOME, TB_CLASSES.NOME, TB_CLASSES.DESCRICAO, TB_PERSONAGENS.ATAQUE,TB_PERSONAGENS.DEFESA FROM TB_PERSONAGENS INNER JOIN TB_CLASSES ON TB_CLASSES.ID = TB_PERSONAGENS.CLASSE_ID WHERE TB_CLASSES.NOME = "Dark Knight";






