CREATE DATABASE DB_ESCOLA_ESTADUAL;

USE DB_ESCOLA_ESTADUAL;
  
  CREATE TABLE TB_ESTUDANTES(
  ID BIGINT AUTO_INCREMENT,
  NOME VARCHAR(255),
  IDADE INT,
  TURMA VARCHAR(255),
  NOTA DOUBLE,
  PRIMARY KEY (ID)  
  );
  
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('JOAO',6,'1ªB',7.5);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('MARIA',8,'3ªA',8.0);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('JOSE',7,'5ªC',8.5);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('ENZO',9,'4ªD',5.0);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('VALENTINA',6,'1ªA',9.0);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('PEDRO',8,'3ªB',6.5);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('TIAGO',7,'5ªC',4.5);
INSERT INTO TB_ESTUDANTES (NOME,IDADE,TURMA,NOTA) VALUES ('JULIA',9,'4ªB',10);

SELECT * FROM TB_ESTUDANTES WHERE NOTA > 7.0;
SELECT * FROM TB_ESTUDANTES WHERE NOTA < 7.0;

UPDATE TB_ESTUDANTES SET NOTA = 5.0 WHERE ID = 7
   
   