CREATE DATABASE DB_ECOMMERCE;

USE DB_ECOMMERCE;

CREATE TABLE TB_PRODUTOS(
ID BIGINT AUTO_INCREMENT,
MARCA VARCHAR(255),
MODELO VARCHAR(255),
COR CHAR(255),
PREÇO DOUBLE,
PRIMARY KEY(ID)
);

INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('MOTOROLA','MOTO G 71','PRETO',1870);
INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('SONY','XPERIA Z5','DOURADO',2100);
INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('LG','K62','BRANCO',1500);
INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('SAMSUNG','GALAX A13','VERMELHO',1439);
INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('ASUS','ZENFONE 8','PRETO',3650);
INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('APPLE','IPHONE 11','BRANCO',3599);
INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('XIAOMI','NOTE 11','PRETO',1255);
INSERT INTO TB_PRODUTOS (MARCA,MODELO,COR,PREÇO) VALUES ('MULTILASER','LITE','BRANCO',350);

SELECT * FROM TB_PRODUTOS WHERE PREÇO > 500;
SELECT * FROM TB_PRODUTOS WHERE PREÇO < 500;

UPDATE TB_PRODUTOS SET PREÇO = 600 WHERE ID = 6; 

